spring.application.name=backend
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://suriya1252004_db_user:admin@cluster0.fhzgdk4.mongodb.net/cravekart?appName=Cluster0

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
